# SARIMA Training Configuration
# Konfigurasi untuk penelitian: "Peramalan Indikator Rumah Sakit Berbasis Sensus Harian Rawat Inap dengan Model SARIMA"

# Database Configuration
database:
  path: "../db/sensus.db"  # Backend db directory with the training data
  table: "sensus_harian"
  date_column: "tanggal"
  target_column: "bor"  # Bed Occupancy Rate

# Data Preprocessing
data:
  train_test_split: 0.8  # 80% training, 20% testing
  outlier_method: "iqr"  # Interquartile Range method
  missing_value_strategy: "forward_fill"
  min_data_points: 25  # Minimum data points required

# SARIMA Parameters for Grid Search (IMPROVED for RSJ data)
sarima:
  # Non-seasonal parameters (p,d,q)
  p_range: [0, 1, 2]     # AutoRegressive order
  d_range: [0, 1]        # Differencing order
  q_range: [0, 1, 2]     # Moving Average order
  
  # Seasonal parameters (P,D,Q,s) - EXPANDED for better coverage
  P_range: [0, 1, 2]        # Seasonal AR - EXPANDED from [0,1] to [0,1,2]
  D_range: [0, 1]           # Seasonal Differencing - EXPANDED from [0] to [0,1]
  Q_range: [0, 1, 2]        # Seasonal MA - EXPANDED from [0,1] to [0,1,2]
  seasonal_periods: [7, 14, 30]  # Weekly, Bi-weekly, Monthly - EXPANDED for RSJ patterns
  
  # Model fitting parameters
  method: "lbfgs"        # Optimization method
  maxiter: 200           # Maximum iterations
  enforce_stationarity: false   # More flexible for RSJ data
  enforce_invertibility: false  # More flexible for RSJ data

# Performance Criteria (adjusted for RSJ with low BOR)
performance:
  target_mape: 50.0      # Adjusted for RSJ (low BOR inflates MAPE)
  target_rmse: 10.0      # Adjusted for RSJ data range
  target_mae: 5.0        # PRIMARY METRIC for RSJ (more robust)
  primary_metric: "mae"  # MAE is primary for low BOR values

# Output Configuration
output:
  model_file: "sarima_model.pkl"
  log_file: "training_log.json"
  plots_enabled: true
  verbose: true

# Model Selection Criteria
model_selection:
  primary_metric: "aic"   # Primary: AIC (Akaike Information Criterion)
  secondary_metric: "bic" # Secondary: BIC (Bayesian Information Criterion)
  validate_residuals: true
  ljung_box_alpha: 0.05   # Significance level for residual tests