# SARIMA Training Configuration
# Konfigurasi untuk penelitian: "Peramalan Indikator Rumah Sakit Berbasis Sensus Harian Rawat Inap dengan Model SARIMA"

# Database Configuration
database:
  path: "../db/sensus.db"  # Backend db directory with the training data
  table: "sensus_harian"
  date_column: "tanggal"
  target_column: "bor"  # Bed Occupancy Rate

# Data Preprocessing
data:
  train_test_split: 0.8  # 80% training, 20% testing
  outlier_method: "iqr"  # Interquartile Range method
  missing_value_strategy: "forward_fill"
  min_data_points: 25  # Minimum data points required

# SARIMA Parameters for Grid Search (OPTIMIZED for large dataset)
sarima:
  # Non-seasonal parameters (p,d,q) - REDUCED for speed
  p_range: [0, 1, 2]     # AutoRegressive order
  d_range: [0, 1]        # Differencing order (most data stationary/need 1 diff)
  q_range: [0, 1, 2]     # Moving Average order
  
  # Seasonal parameters (P,D,Q,s) - FOCUSED on weekly pattern
  P_range: [0, 1]        # Seasonal AutoRegressive order
  D_range: [0]           # Seasonal Differencing order (usually 0)
  Q_range: [0, 1]        # Seasonal Moving Average order
  seasonal_periods: [7]  # Weekly (7) pattern only - most relevant for hospital
  
  # Model fitting parameters - OPTIMIZED for speed
  method: "lbfgs"        # Optimization method
  maxiter: 500           # Reduced iterations
  enforce_stationarity: true   # Faster convergence
  enforce_invertibility: true  # Faster convergence

# Performance Criteria (sesuai standar jurnal)
performance:
  target_mape: 10.0      # Target MAPE < 10%
  target_rmse: 5.0       # Target RMSE < 5%
  target_mae: 4.0        # Target MAE < 4%

# Output Configuration
output:
  model_file: "sarima_model.pkl"
  log_file: "training_log.json"
  plots_enabled: true
  verbose: true

# Model Selection Criteria
model_selection:
  primary_metric: "aic"   # Primary: AIC (Akaike Information Criterion)
  secondary_metric: "bic" # Secondary: BIC (Bayesian Information Criterion)
  validate_residuals: true
  ljung_box_alpha: 0.05   # Significance level for residual tests