# SARIMA Training Configuration
# Konfigurasi untuk penelitian: "Peramalan Indikator Rumah Sakit Berbasis Sensus Harian Rawat Inap dengan Model SARIMA"

# Database Configuration
database:
  path: "../db/sensus.db"  # Backend db directory with the training data
  table: "sensus_harian"
  date_column: "tanggal"
  target_column: "bor"  # Bed Occupancy Rate

# Data Preprocessing
data:
  train_test_split: 0.8  # 80% training, 20% testing
  outlier_method: "iqr"  # Interquartile Range method
  missing_value_strategy: "forward_fill"
  min_data_points: 25  # Minimum data points required

# SARIMA Parameters for Grid Search
sarima:
  # Non-seasonal parameters (p,d,q)
  p_range: [0, 1, 2, 3]  # AutoRegressive order
  d_range: [0, 1, 2]     # Differencing order
  q_range: [0, 1, 2, 3]  # Moving Average order
  
  # Seasonal parameters (P,D,Q,s)
  P_range: [0, 1, 2]     # Seasonal AutoRegressive order
  D_range: [0, 1]        # Seasonal Differencing order
  Q_range: [0, 1, 2]     # Seasonal Moving Average order
  seasonal_periods: [7, 30]  # Weekly (7) and Monthly (30) patterns
  
  # Model fitting parameters
  method: "lbfgs"        # Optimization method
  maxiter: 1000          # Maximum iterations
  enforce_stationarity: false
  enforce_invertibility: false

# Performance Criteria (sesuai standar jurnal)
performance:
  target_mape: 10.0      # Target MAPE < 10%
  target_rmse: 5.0       # Target RMSE < 5%
  target_mae: 4.0        # Target MAE < 4%

# Output Configuration
output:
  model_file: "sarima_model.pkl"
  log_file: "training_log.json"
  plots_enabled: true
  verbose: true

# Model Selection Criteria
model_selection:
  primary_metric: "aic"   # Primary: AIC (Akaike Information Criterion)
  secondary_metric: "bic" # Secondary: BIC (Bayesian Information Criterion)
  validate_residuals: true
  ljung_box_alpha: 0.05   # Significance level for residual tests